
MAJOR_REPORT_VERSION = 1
MINOR_REPORT_VERSION = 1
PATCH_REPORT_VERSION = 1

REPORT_GENERATOR_VERSION = f"{MAJOR_REPORT_VERSION}.{MINOR_REPORT_VERSION}.{PATCH_REPORT_VERSION}"

def get_report_generator_version() -> str:
    return REPORT_GENERATOR_VERSION
